### ISSUE TITLE
Convert from Psalm plugin to laminas-cli command

### ISSUE THREAD

**Issue by weierophinney** [zakirullin/laminas-psalm-plugin#2]
As discussed in the technical steering committee meeting on 2020-03-01, the intention is for this to operate as a standalone laminas-cli command, instead of a Psalm plugin, to allow more flexibility in use, as well as the ability to use in both development and production.

**Comment by zakirullin** [comment]
Closed with https://github.com/laminas/laminas-servicemanager-inspector/commit/752e9ad246ba10bc47981d31f8ed3d1b667ad0c0
